# Generated by Django 3.2.25 on 2024-12-22 13:28

import cloudinary.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=254)),
                ('last_name', models.CharField(max_length=254)),
                ('is_crafter', models.BooleanField()),
                ('is_admin', models.BooleanField()),
                ('craft_time_commited', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('craft_time_max', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('deleted_on', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auth_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
