# Generated by Django 3.2.25 on 2024-12-27 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='customisation',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
