# Generated by Django 3.2.25 on 2025-01-26 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20250126_1351'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlineitem',
            name='customization',
        ),
        migrations.AddField(
            model_name='order',
            name='customization',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
