# Generated by Django 3.2.25 on 2024-12-17 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='deleted_on',
            field=models.DateTimeField(null=True),
        ),
    ]
